### ISSUE TITLE
Consumers consume multiple partiton in topic Kafka

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb-binlog#1018]
Hi all.
Because I will use consumers to consume data from Kafka, so I need the producer to push data to multiple partitions.
So I can customize Drainer to push data to multiple partitions instead of a partition 0 like an implementation of Tidb-Binlog.
Does something go wrong when I do?
@july2993

**Comment by july2993** [comment]
drainer does not support pushing to multiple partitions now, and there' no plan to do it because it's supposed to use https://github.com/pingcap/ticdc in the future.

Nothing special goes wrong if you do want to customize the drainer to support it, you need the decide how to distribute data to multiple partitions.

**Comment by phamtai97** [comment]
Thanks for your answer.
